set hive.auto.convert.join = false;
set hive.limit.optimize.enable=true;
set hive.exec.reducers.max=100;
set hive.exec.reducers.bytes.per.reducer=500000000;

DROP TABLE IF EXISTS risk_features.zzr_model3_hive;
CREATE TABLE risk_features.zzr_model3_hive
AS
SELECT 
t1.luserid, --客户编号
t1.strname, --姓名
t1.ngrantstate, --客户目前的账户状态
t1.identity, --身份证号
t1.province, --身份证的省份
t1.spouse_identity, --配偶省份证号
t1.nsex, --性别{1:男,2:女}
t1.age, --年龄
t1.company_duty_name, --职务名称
t1.working_days_of_current_job, --基础授信时目前这份工作天数
t1.monthly_income, --月收入
t1.house_type_name, --住房类型
t1.marriage, --婚姻状态
t1.child_count, --子女数量
t1.qq, --qq号
t1.wechat, --微信号
t1.whether_fill_property_info, --是否填写资产信息
t1.education_name, --受教育水平
t1.credit_mobile, --基础授信时填写的手机号
t1.credit_bank_reservemobile, --银行卡预留手机号
t1.mobf3_in_170171177, --手机号前三位是否命中(170,171,177)
t1.whether_change_mobile_number, --是否更改过手机号
t1.mobile_number_equal_bank_mobile, --基础授信时手机号是否与银行卡预留手机号相同
t1.credit_emergency_tel, --紧急联系人手机号
t1.emergency_contact_mobf3_in_170171177, --紧急联系人手机号前三位是否命中(170,171,177)
t1.inner_sec_code, --客户来源（神秘编码）
t1.borrow_type_name, --借款类型
t1.words_of_salesman, --基础授信时销售员备注长度
t1.words_of_manager, --基础授信时经理备注长度
t1.refused_times, --基础授信通过时，曾被拒的次数
t1.returned_times, --基础授信通过时，曾被退回的次数
t1.credit_audit_time, --基础授信通过的时间
t1.credit_approval_amount, --基础授信通过时的额度
t1.credit_salesman_id, --基础授信时的业务员ID
t1.current_salesman_id, --目前的业务员ID
t1.credit_salesman_mobile, --基础授信时的业务员手机号
t1.credit_salesman_name, --基础授信时的业务员姓名
t1.current_dept_id, --目前的营业部ID
t1.credit_dept_code, --基础授信时的营业部编码
t1.credit_dept_name, --基础授信时的营业部名称
t1.strauditprimaryid, --基础授信时的初审ID
t1.strauditprimaryname, --基础授信时的初审姓名
t1.strauditprimaryrole, --基础授信时的初审职级
t1.strauditseniorid, --基础授信时的终审ID
t1.strauditseniorname, --基础授信时的终审姓名
t1.strauditseniorrole, --基础授信时的终审职级
t1.credit_salesman_overdue_ratio, --客户基础授信所属业务员本金逾期率（金额维度）
t1.credit_salesman_overdue_amount, --客户基础授信所属业务员逾期金额
t1.current_salesman_overdue_ratio, --客户目前所属业务员本金逾期率（金额维度）
t1.current_salesman_overdue_amount, --客户目前所属业务员逾期金额
t1.credit_dept_overdue_ratio, --客户基础授信所属营业部本金逾期率（金额维度）
t1.credit_dept_overdue_amount, --客户基础授信所属营业部逾期金额
t1.current_dept_overdue_ratio, --客户目前所属营业部本金逾期率（金额维度）
t1.current_dept_overdue_amount, --客户目前所属营业部逾期金额
t2.loan_times, --客户借款次数
t2.loan_times_last_3months, --客户最近3个月借款次数
t2.loan_times_last_6months, --客户最近6个月借款次数
t2.loan_times_last_9months, --客户最近9个月借款次数
t2.loan_times_last_12months, --客户最近12个月借款次数
t2.loan_total_amount, --客户总借款金额
t2.loan_total_amount_last_3months, --客户最近3个月借款金额
t2.loan_total_amount_last_6months, --客户最近6个月借款金额
t2.loan_total_amount_last_9months, --客户最近9个月借款金额
t2.loan_total_amount_last_12months, --客户最近12个月借款金额
t2.loan_max_amount, --客户单笔最大借款金额
t2.loan_max_amount_last_3months, --客户最近3个月单笔最大借款金额
t2.loan_max_amount_last_6months, --客户最近6个月单笔最大借款金额
t2.loan_max_amount_last_9months, --客户最近9个月单笔最大借款金额
t2.loan_max_amount_last_12months, --客户最近12个月单笔最大借款金额
t2.expire_times, --已到期借款的笔数
t2.expire_times_last_3months, --到期日在最近3个月内的借款的笔数
t2.expire_times_last_6months, --到期日在最近6个月内的借款的笔数
t2.expire_times_last_9months, --到期日在最近9个月内的借款的笔数
t2.expire_times_last_12months, --到期日在最近12个月内的借款的笔数
t2.ontime_times, --已到期借款的按时还清笔数
t2.ontime_times_last_3months, --到期日在最近3个月内的借款的按时还清笔数
t2.ontime_times_last_6months, --到期日在最近6个月内的借款的按时还清笔数
t2.ontime_times_last_9months, --到期日在最近9个月内的借款的按时还清笔数
t2.ontime_times_last_12months, --到期日在最近12个月内的借款的按时还清笔数
t2.overdue_times, --已到期借款的逾期笔数
t2.overdue_times_last_3months, --到期日在最近3个月内的借款的逾期笔数
t2.overdue_times_last_6months, --到期日在最近6个月内的借款的逾期笔数
t2.overdue_times_last_9months, --到期日在最近9个月内的借款的逾期笔数
t2.overdue_times_last_12months, --到期日在最近12个月内的借款的逾期笔数
t2.prepay_times, --已到期借款的提前还清笔数
t2.prepay_times_last_3months, --到期日在最近3个月内的借款的提前还清笔数
t2.prepay_times_last_6months, --到期日在最近6个月内的借款的提前还清笔数
t2.prepay_times_last_9months, --到期日在最近9个月内的借款的提前还清笔数
t2.prepay_times_last_12months, --到期日在最近12个月内的借款的提前还清笔数
t2.expire_total_amount, --已到期借款的总放款金额
t2.expire_total_amount_last_3months, --到期日在最近3个月内的借款的总放款金额
t2.expire_total_amount_last_6months, --到期日在最近6个月内的借款的总放款金额
t2.expire_total_amount_last_9months, --到期日在最近9个月内的借款的总放款金额
t2.expire_total_amount_last_12months, --到期日在最近12个月内的借款的总放款金额
t2.expire_max_amount, --已到期借款的单笔最大放款金额
t2.expire_max_amount_last_3months, --到期日在最近3个月内的借款的单笔最大放款金额
t2.expire_max_amount_last_6months, --到期日在最近6个月内的借款的单笔最大放款金额
t2.expire_max_amount_last_9months, --到期日在最近9个月内的借款的单笔最大放款金额
t2.expire_max_amount_last_12months, --到期日在最近12个月内的借款的单笔最大放款金额
t2.ontime_total_amount, --已到期借款的按时还清金额（该笔合同全部按时还清才算）
t2.ontime_total_amount_last_3months, --到期日在最近3个月内的借款的按时还清金额
t2.ontime_total_amount_last_6months, --到期日在最近6个月内的借款的按时还清金额
t2.ontime_total_amount_last_9months, --到期日在最近9个月内的借款的按时还清金额
t2.ontime_total_amount_last_12months, --到期日在最近12个月内的借款的按时还清金额
t2.ontime_max_amount, --已到期借款的单笔最大按时还清金额
t2.ontime_max_amount_last_3months, --到期日在最近3个月内的借款的单笔最大按时还清金额
t2.ontime_max_amount_last_6months, --到期日在最近6个月内的借款的单笔最大按时还清金额
t2.ontime_max_amount_last_9months, --到期日在最近9个月内的借款的单笔最大按时还清金额
t2.ontime_max_amount_last_12months, --到期日在最近12个月内的借款的单笔最大按时还清金额
t2.overdue_total_amount, --已到期借款中逾期借款的总放款金额
t2.overdue_total_amount_last_3months, --到期日在最近3个月内的逾期借款的总放款金额
t2.overdue_total_amount_last_6months, --到期日在最近6个月内的逾期借款的总放款金额
t2.overdue_total_amount_last_9months, --到期日在最近9个月内的逾期借款的总放款金额
t2.overdue_total_amount_last_12months, --到期日在最近12个月内的逾期借款的总放款金额
t2.overdue_max_amount, --已到期借款中逾期借款的单笔最大放款金额
t2.overdue_max_amount_last_3months, --到期日在最近3个月内的逾期借款的单笔最大放款金额
t2.overdue_max_amount_last_6months, --到期日在最近6个月内的逾期借款的单笔最大放款金额
t2.overdue_max_amount_last_9months, --到期日在最近9个月内的逾期借款的单笔最大放款金额
t2.overdue_max_amount_last_12months, --到期日在最近12个月内的逾期借款的单笔最大放款金额
t2.prepay_total_amount, --已到期借款中提前还清金额
t2.prepay_total_amount_last_3months, --到期日在最近3个月内的借款的提前还清金额
t2.prepay_total_amount_last_6months, --到期日在最近6个月内的借款的提前还清金额
t2.prepay_total_amount_last_9months, --到期日在最近9个月内的借款的提前还清金额
t2.prepay_total_amount_last_12months, --到期日在最近12个月内的借款的提前还清金额
t2.prepay_max_amount, --已到期借款中单笔最大提前还清金额
t2.prepay_max_amount_last_3months, --到期日在最近3个月内的借款的单笔最大提前还清金额
t2.prepay_max_amount_last_6months, --到期日在最近6个月内的借款的单笔最大提前还清金额
t2.prepay_max_amount_last_9months, --到期日在最近9个月内的借款的单笔最大提前还清金额
t2.prepay_max_amount_last_12months, --到期日在最近12个月内的借款的单笔最大提前还清金额
t2.ontime_amount, --已到期借款中按时还款金额
t2.ontime_amount_last_3months, --到期日在最近3个月内的借款的按时还款金额
t2.ontime_amount_last_6months, --到期日在最近6个月内的借款的按时还款金额
t2.ontime_amount_last_9months, --到期日在最近9个月内的借款的按时还款金额
t2.ontime_amount_last_12months, --到期日在最近12个月内的借款的按时还款金额
t2.overdue_amount, --已到期借款中逾期金额
t2.overdue_amount_last_3months, --到期日在最近3个月内的借款的逾期未还金额
t2.overdue_amount_last_6months, --到期日在最近6个月内的借款的逾期未还金额
t2.overdue_amount_last_9months, --到期日在最近9个月内的借款的逾期未还金额
t2.overdue_amount_last_12months, --到期日在最近12个月内的借款的逾期未还金额
t2.prepay_amount, --已到期借款中提前还款金额
t2.prepay_amount_last_3months, --到期日在最近3个月内的借款的提前还款金额
t2.prepay_amount_last_6months, --到期日在最近6个月内的借款的提前还款金额
t2.prepay_amount_last_9months, --到期日在最近9个月内的借款的提前还款金额
t2.prepay_amount_last_12months, --到期日在最近12个月内的借款的提前还款金额
t2.observation_overdue1day_times, --可观测逾期1天的借款笔数
t2.observation_overdue5day_times, --可观测逾期5天的借款笔数
t2.observation_overdue10day_times, --可观测逾期10天的借款笔数
t2.observation_overdue30day_times, --可观测逾期30天的借款笔数
t2.observation_overdue60day_times, --可观测逾期60天的借款笔数
t2.observation_overdue90day_times, --可观测逾期90天的借款笔数
t2.overdue_1day_times, --可观测逾期1天的借款中逾期1天笔数
t2.overdue_5day_times, --可观测逾期5天的借款中逾期5天笔数
t2.overdue_10day_times, --可观测逾期10天的借款中逾期10天笔数
t2.overdue_30day_times, --可观测逾期30天的借款中逾期30天笔数
t2.overdue_60day_times, --可观测逾期60天的借款中逾期60天笔数
t2.overdue_90day_times, --可观测逾期90天的借款中逾期90天笔数
t2.observation_overdue1day_amount, --可观测逾期1天的借款金额
t2.observation_overdue5day_amount, --可观测逾期5天的借款金额
t2.observation_overdue10day_amount, --可观测逾期10天的借款金额
t2.observation_overdue30day_amount, --可观测逾期30天的借款金额
t2.observation_overdue60day_amount, --可观测逾期60天的借款金额
t2.observation_overdue90day_amount, --可观测逾期90天的借款金额
t2.overdue1day_amount, --可观测逾期1天的借款中逾期1天未还金额
t2.overdue5day_amount, --可观测逾期5天的借款中逾期5天未还金额
t2.overdue10day_amount, --可观测逾期10天的借款中逾期10天未还金额
t2.overdue30day_amount, --可观测逾期30天的借款中逾期30天未还金额
t2.overdue60day_amount, --可观测逾期60天的借款中逾期60天未还金额
t2.overdue90day_amount, --可观测逾期90天的借款中逾期90天未还金额
t2.overdue1day_total_amount, --可观测逾期1天的借款中逾期1天的借款对应的放款金额加总
t2.overdue5day_total_amount, --可观测逾期5天的借款中逾期5天的借款对应的放款金额加总
t2.overdue10day_total_amount, --可观测逾期10天的借款中逾期10天的借款对应的放款金额加总
t2.overdue30day_total_amount, --可观测逾期30天的借款中逾期30天的借款对应的放款金额加总
t2.overdue60day_total_amount, --可观测逾期60天的借款中逾期60天的借款对应的放款金额加总
t2.overdue90day_total_amount, --可观测逾期90天的借款中逾期90天的借款对应的放款金额加总
t2.observation_overdue30day_time_last_12months, --到期日在最近12个月内的借款中，能观测到逾期30天的笔数
t2.overdue_30day_times_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的笔数
t2.overdue30day_total_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同总金额
t2.overdue30day_max_total_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同的最大金额
t2.overdue30day_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同其逾期了30天未还的金额
t2.overdue30day_max_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同其逾期了30天未还的最大金额
t2.observation_overdue60day_time_last_12months, --到期日在最近12个月内的借款中，能观测到逾期30天的笔数
t2.overdue_60day_times_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的笔数
t2.overdue60day_total_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同总金额
t2.overdue60day_max_total_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同的最大金额
t2.overdue60day_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同其逾期了30天未还的金额
t2.overdue60day_max_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同其逾期了30天未还的最大金额
t2.observation_overdue90day_time_last_12months, --到期日在最近12个月内的借款中，能观测到逾期30天的笔数
t2.overdue_90day_times_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的笔数
t2.overdue90day_total_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同总金额
t2.overdue90day_max_total_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同的最大金额
t2.overdue90day_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同其逾期了30天未还的金额
t2.overdue90day_max_amount_last_12months, --到期日在最近12个月内的借款中，逾期超过30天的合同其逾期了30天未还的最大金额
t2.onway_overdue_days_max, --客户目前未还借款中，逾期的最大天数
t2.onway_loan_times, --客户目前未还借款笔数
t2.onway_overdue_times, --客户目前未还借款中处于逾期状态的笔数
t2.onway_overdue1day_times, --客户目前未还借款中处于逾期1天状态的笔数
t2.onway_overdue5day_times, --客户目前未还借款中处于逾期5天状态的笔数
t2.onway_overdue10day_times, --客户目前未还借款中处于逾期10天状态的笔数
t2.onway_overdue30day_times, --客户目前未还借款中处于逾期30天状态的笔数
t2.onway_overdue60day_times, --客户目前未还借款中处于逾期60天状态的笔数
t2.onway_overdue90day_times, --客户目前未还借款中处于逾期90天状态的笔数
t2.onway_overdue180day_times, --客户目前未还借款中处于逾期180天状态的笔数
t2.onway_amount, --客户目前未还金额
t2.onway_30day_toenddate_amount, --借款有多少在30天内即将到期
t2.onway_overdue_amount, --客户目前未还金额中处于逾期状态的金额
t2.onway_overdue1day_amount, --客户目前未还金额中处于逾期1天状态的金额
t2.onway_overdue5day_amount, --客户目前未还金额中处于逾期5天状态的金额
t2.onway_overdue10day_amount, --客户目前未还金额中处于逾期10天状态的金额
t2.onway_overdue30day_amount, --客户目前未还金额中处于逾期30天状态的金额
t2.onway_overdue60day_amount, --客户目前未还金额中处于逾期60天状态的金额
t2.onway_overdue90day_amount, --客户目前未还金额中处于逾期90天状态的金额
t2.onway_overdue180day_amount, --客户目前未还金额中处于逾期180天状态的金额
t2.last_overdue1days_enddate_before_present, --最近一次的1天或以上逾期，应还日离现在多少天
t2.last_overdue5days_enddate_before_present, --最近一次的5天或以上逾期，应还日离现在多少天
t2.last_overdue10days_enddate_before_present, --最近一次的10天或以上逾期，应还日离现在多少天
t2.last_overdue30days_enddate_before_present, --最近一次的30天或以上逾期，应还日离现在多少天
t2.last_overdue60days_enddate_before_present, --最近一次的60天或以上逾期，应还日离现在多少天
t2.last_overdue90days_enddate_before_present, --最近一次的90天或以上逾期，应还日离现在多少天
t3.first_loandate, --到期借款中第一笔借款发生时间
t3.first_loan_amount, --到期借款中第一笔借款总金额
t3.first_is_overdue, --到期借款中第一笔借款是否逾期
t3.first_overdue_days, --到期借款中第一笔借款逾期天数
t3.first_overdue_amount, --到期借款中第一笔借款逾期金额
t3.first_is_prepay, --到期借款中第一笔借款是否提前还款
t3.first_prepay_days, --到期借款中第一笔借款提前还款天数
t3.first_prepay_amount, --到期借款中第一笔借款提前还款金额
t4.last_loandate, --到期日在最近12个月内的借款中，最近一笔借款时间
t4.last_loan_amount, --到期日在最近12个月内的借款中，最近一笔借款总金额
t4.last_is_overdue, --到期日在最近12个月内的借款中，最近一笔借款是否逾期
t4.last_overdue_days, --到期日在最近12个月内的借款中，最近一笔借款逾期天数
t4.last_overdue_amount, --到期日在最近12个月内的借款中，最近一笔借款逾期金额
t4.last_is_prepay, --到期日在最近12个月内的借款中，最近一笔借款是否提前还款
t4.last_prepay_days, --到期日在最近12个月内的借款中，最近一笔借款提前还款天数
t4.last_prepay_amount, --到期日在最近12个月内的借款中，最近一笔借款提前还款金额
t5.first_overdue_loandate, --客户最早一笔逾期借款发生时间
datediff(t5.first_overdue_loandate,t1.credit_audit_time) AS time_between_first_overdue_and_audit, --客户最早一笔逾期借款发生时间距离基础授信通过时时间间隔天数
t5.first_overdue_loan_amount, --客户最早一笔逾期借款逾期金额
t5.first_overdue_total_amount, --客户最早一笔逾期借款借款金额
round(t5.first_overdue_total_amount/t1.credit_approval_amount,2) AS first_overde_total_amount_rate, --客户最早一笔逾期借款金额占基础授信时的额度比率 
t6.last_overdue_loandate, --客户最近一笔逾期借款发生时间
t6.last_overdue_loan_amount, --客户最近一笔逾期借款逾期金额
t6.last_overdue_total_amount, --客户最近一笔逾期借款借款金额
t7.first_1term_amount, --首次借款第一期应还金额
t7.first_1term_observation_overdue, --首次借款第一期是否可观测逾期
t7.first_1term_is_overdue, --首次借款第一期是否逾期
t7.first_1term_overdue_days, --首次借款第一期逾期天数
t7.first_1term_overdue_amount, --首次借款第一期逾期金额
t8.last_1term_amount, --最近一次第一期逾期可观测的借款，第一期应还金额
t8.last_1term_is_overdue, --最近一次第一期逾期可观测的借款，第一期是否逾期
t8.last_1term_overdue_days, --最近一次第一期逾期可观测的借款，第一期逾期天数
t8.last_1term_overdue_amount, --最近一次第一期逾期可观测的借款，第一期逾期金额
t9.expire_1st_terms, --借款第一期已到期笔数
t9.expire_1st_terms_last_3months, --借款第一期到期日在最近3个月的笔数
t9.expire_1st_terms_last_6months, --借款第一期到期日在最近6个月的笔数
t9.expire_1st_terms_last_9months, --借款第一期到期日在最近9个月的笔数
t9.expire_1st_terms_last_12months, --借款第一期到期日在最近12个月的笔数
t9.overdue_1st_terms, --借款第一期已到期中逾期笔数
t9.overdue_1st_terms_last_3months, --借款第一期到期日在最近3个月的逾期笔数
t9.overdue_1st_terms_last_6months, --借款第一期到期日在最近6个月的逾期笔数
t9.overdue_1st_terms_last_9months, --借款第一期到期日在最近9个月的逾期笔数
t9.overdue_1st_terms_last_12months, --借款第一期到期日在最近12个月的逾期笔数
t9.expire_1st_term_amount, --借款第一期已到期的应还款金额
t9.expire_1st_term_amount_last_3months, --借款第一期到期日在最近3个月的应还款金额
t9.expire_1st_term_amount_last_6months, --借款第一期到期日在最近6个月的应还款金额
t9.expire_1st_term_amount_last_9months, --借款第一期到期日在最近9个月的应还款金额
t9.expire_1st_term_amount_last_12months, --借款第一期到期日在最近12个月的应还款金额
t9.overdue_1st_term_amount, --借款第一期已到期的逾期金额
t9.overdue_1st_term_amount_last_3months, --借款第一期到期日在最近3个月的逾期金额
t9.overdue_1st_term_amount_last_6months, --借款第一期到期日在最近6个月的逾期金额
t9.overdue_1st_term_amount_last_9months, --借款第一期到期日在最近9个月的逾期金额
t9.overdue_1st_term_amount_last_12months, --借款第一期到期日在最近12个月的逾期金额
t9.expire_terms, --已到期的期数（本金及利息）
t9.expire_terms_last_3months, --借款第N期到期日在最近3个月的期数
t9.expire_terms_last_6months, --借款第N期到期日在最近6个月的期数
t9.expire_terms_last_9months, --借款第N期到期日在最近9个月的期数
t9.expire_terms_last_12months, --借款第N期到期日在最近12个月的期数
t9.overdue_terms, --借款第N期已到期中逾期期数
t9.onway_overdue_terms, --客户目前未还借款中处于逾期状态的期数
t9.overdue_terms_last_3months, --借款第N期到期日在最近3个月的逾期期数
t9.overdue_terms_last_6months, --借款第N期到期日在最近6个月的逾期期数
t9.overdue_terms_last_9months, --借款第N期到期日在最近9个月的逾期期数
t9.overdue_terms_last_12months, --借款第N期到期日在最近12个月的逾期期数
t9.expire_term_amount, --借款第N期已到期的应还款金额
t9.expire_term_amount_last_3months, --借款第N期到期日在最近3个月的应还款金额
t9.expire_term_amount_last_6months, --借款第N期到期日在最近6个月的应还款金额
t9.expire_term_amount_last_9months, --借款第N期到期日在最近9个月的应还款金额
t9.expire_term_amount_last_12months, --借款第N期到期日在最近12个月的应还款金额
t9.overdue_term_amount, --借款第N期已到期的逾期金额
t9.overdue_term_amount_last_3months, --借款第N期到期日在最近3个月的逾期金额
t9.overdue_term_amount_last_6months, --借款第N期到期日在最近6个月的逾期金额
t9.overdue_term_amount_last_9months, --借款第N期到期日在最近9个月的逾期金额
t9.overdue_term_amount_last_12months, --借款第N期到期日在最近12个月的逾期金额
t10.spouse_is_client, --配偶是否属于达飞客户
t10.spouse_loan_times, --配偶借款次数
t10.spouse_loan_total_amount, --配偶借款总金额
t10.spouse_overdue_times, --配偶逾期次数
t10.spouse_onway_amount, --配偶第一次借款第一期是否逾期
t10.spouse_first_1term_is_overdue, --配偶目前在库金额
t11.contact_is_client, --联系人是否属于达飞客户
t11.contact_loan_times, --联系人借款次数
t11.contact_loan_total_amount, --联系人借款总金额
t11.contact_overdue_times, --联系人逾期次数
t11.contact_onway_amount, --联系人第一次借款第一期是否逾期
t11.contact_first_1term_is_overdue, --联系人目前在库金额
t12.y1,-- 到期日在4月1日往后6个月内，逾期60天金额累计超过1000为1；6个月内未逾期为0
t12.y2,-- 借款日及到期日均在4月1日往后7个月内，逾期60天金额累计超过1000为1；7个月内未逾期为0
t12.y3,-- 借款日及到期日均在4月1日往后7个月内，逾期30天金额累计超过1000为1；7个月内未逾期为0
t12.y4,
t12.y5
FROM risk_features.zzr_model3_audit t1
LEFT JOIN risk_features.zzr_model3_repayment t2 ON t1.luserid=t2.lborrowerid
LEFT JOIN risk_features.zzr_model3_first_repayment t3 ON t1.luserid=t3.lborrowerid
LEFT JOIN risk_features.zzr_model3_last_repayment t4 ON t1.luserid=t4.lborrowerid
LEFT JOIN risk_features.zzr_model3_first_overdue_repayment t5 ON t1.luserid=t5.lborrowerid
LEFT JOIN risk_features.zzr_model3_last_overdue_repayment t6 ON t1.luserid=t6.lborrowerid
LEFT JOIN risk_features.zzr_model3_first_1term_repayment t7 ON t1.luserid=t7.lborrowerid
LEFT JOIN risk_features.zzr_model3_last_1term_repayment t8 ON t1.luserid=t8.lborrowerid
LEFT JOIN risk_features.zzr_model3_nterms_repayment t9 ON t1.luserid=t9.lborrowerid
LEFT JOIN risk_features.zzr_model3_spouse t10 ON t1.luserid=t10.luserid
LEFT JOIN risk_features.zzr_model3_contact t11 ON t1.luserid=t11.user_id
LEFT JOIN risk_features.zzr_model3_y t12 ON t1.luserid=t12.lborrowerid
;